### ISSUE TITLE
Link handler not working

### ISSUE THREAD

**Issue by JohnSpahr** [Pocket-PC-Planet/PPCP-AppManager#29]
Nothing happens, no messages appear when enabled in dev mode when link clicked. Tested on WM5 HP iPAQ rx1955.

**Comment by carcarjg** [comment]
What version of .net Is installed?

**Comment by JohnSpahr** [comment]
3.5, I believe. I can test again. Maybe I was just clicking the links too fast. :/

**Comment by carcarjg** [comment]
I was testing on X51s with 3.5 loaded. It's a 2.0 application. Is there some difference between how the HP handles it? I don't think clicking too fast was the problem. I just tried spamming the download button and after the first one it locks up due to the download then downloads correctly. I think HPs are doing something janky.

**Comment by JohnSpahr** [comment]
Hmm, weird. Can you send me the latest version of the client on the AppManager channel on Discord?

**Comment by carcarjg** [comment]
The one I posed is the latest working version. I haven't implemented any fixes yet.

**Comment by carcarjg** [comment]
Issue moved to "todo". This will not be fixed in the release version.

**Comment by carcarjg** [comment]
Caused by the Browser control existing in a tabpage control. Dont know why. Dont know how. But this is the issue.

**Comment by JohnSpahr** [comment]
It’s fixed!
